name: 'GitHub Issue Analyzer'

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  gemini-issue-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run Gemini issue analysis'
        uses: 'google-github-actions/run-gemini-cli@v0'
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ISSUE_NUMBER: '${{ github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
        with:
          prompt: |-
            You are a helpful AI assistant.
            Your task is to analyze the title and body of a GitHub issue and provide a helpful comment.
            The issue title is: "${{ github.event.issue.title }}"
            The issue body is: "${{ github.event.issue.body }}"
            Based on the issue, provide a constructive comment. This could be a question for clarification, a suggestion, or an answer.
            Use the mcp__github__create_issue_comment tool to post your response.