name: 'GitHub Issue Analyzer'

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  gemini-issue-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Configure Gemini Settings from file'
        run: |
          mkdir -p /home/runner/.gemini/
          if [ -f ".gemini/settings.json" ]; then
            cp .gemini/settings.json /home/runner/.gemini/settings.json
            echo "Gemini settings configured."
          else
            echo "ERROR: .gemini/settings.json not found!"
            exit 1
          fi
        shell: bash

      - name: 'Run Gemini issue analysis'
        uses: 'google-github-actions/run-gemini-cli@v0'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ISSUE_NUMBER: '${{ github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
        with:
          prompt: |-
            You are a helpful AI assistant.
            Your task is to analyze the title and body of a GitHub issue and provide a helpful comment.
            The issue title is: "${{ github.event.issue.title }}"
            The issue body is: "${{ github.event.issue.body }}"
            Based on the issue, provide a constructive comment. This could be a question for clarification, a suggestion, or an answer.
            Use the mcp__github__create_issue_comment tool to post your response.
