name: 'Pull Request Review'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize]

permissions:         # 👈 must be top-level for reusable workflows
  contents: read     # allow reading repo contents
  pull-requests: write  # allow writing PR comments, reviews, etc.

jobs:
  gemini-review:
    uses: ./.github/workflows/gemini-review.yml
    secrets: inherit
