name: 'Pull Request Review'

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run Gemini pull request review'
        uses: 'google-github-actions/run-gemini-cli@v0'
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PULL_REQUEST_NUMBER: '${{ github.event.pull_request.number }}'
          REPOSITORY: '${{ github.repository }}'
        with:
          prompt: |-
            You are a world-class code reviewer.
            Your task is to analyze the pull request diff and provide feedback.
            Use the mcp__github__get_pull_request_diff tool to get the changes.
            For each issue you find, use the mcp__github__add_comment_to_pending_review tool to add a comment.
            Focus on correctness, security, and maintainability.
            After adding all comments, submit the review using mcp__github__submit_pending_pull_request_review with a brief summary.
