name: 'Pull Request Review'

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Configure Gemini Settings from file'
        run: |
          mkdir -p /home/runner/.gemini/
          if [ -f ".gemini/settings.json" ]; then
            cp .gemini/settings.json /home/runner/.gemini/settings.json
            echo "Gemini settings configured."
          else
            echo "ERROR: .gemini/settings.json not found!"
            exit 1
          fi
        shell: bash

      - name: 'Run Gemini pull request review'
        uses: 'google-github-actions/run-gemini-cli@v0'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PULL_REQUEST_NUMBER: '${{ github.event.pull_request.number }}'
          REPOSITORY: '${{ github.repository }}'
        with:
          prompt: |-
            You are a world-class code reviewer.
            Your task is to analyze the pull request diff and provide feedback.
            Use the mcp__github__get_pull_request_diff tool to get the changes.
            For each issue you find, use the mcp__github__add_comment_to_pending_review tool to add a comment.
            Focus on correctness, security, and maintainability.
            After adding all comments, submit the review using mcp__github__submit_pending_pull_request_review with a brief summary.